export default {
  offer: {
    offer_id: '1234560000',
    campaign_id: '1234570000',
    offer_update_ind: 'Y',
    updated_fields: ['mle_list_id'],
    partner_campaign_id: '',
    partner_offer_id: '',
    partner_reward_id: '',
    test_offer: 'N/Y',
    merchant_name: 'Lowes',
    msg_identifier: '01',
    post_campaign_data_share_ind: 'Y/N',
    post_campaign_data_share_type: 'L4CM15/S',
    setup_system_desc: 'DIMO',
    enrollment_blocked_ind: 'N/Y',
    iso_alpha_2_ctry_cd: 'US',
    source_system_desc: 'RKN/CDLX/GPN',
    campaign_exclusions: [],
    campaign_excluded_at: 'E/F',
    aggregated_time_period: '12',
    renew_at_agg_time_period: 'CD/FTD',
    campaign_details: {
      aggregated_time_period: '',
      campaign_enrollment_cap: '',
      renew_at_agg_time_period: '',
      campaign_exclusions: [],
      campaign_excluded_at: '',
      campaign_max_award_cap: '',
    },
    redemptions: [
      {
        language_cd: 'en',
        rdm_mode_nm: 'online',
        fulfil_type_id: '1',
        char_type_cd: '02',
        char_nm: 'PROMO CODE',
        rdm_mode_char_loc_lang_val_tx: '',
        dia_cd: '03',
      },
      {
        language_cd: 'en',
        rdm_mode_nm: 'in-store',
        fulfil_type_id: '1',
        char_type_cd: '02',
        char_nm: 'PROMO CODE',
        rdm_mode_char_loc_lang_val_tx: '',
        dia_cd: '03',
      },
    ],
    offer_type_cd: 'S',
    disc_type_cd: 'F',
    prog: {
      prog_nm: 'RC Campaign',
      prog_cd: '00000',
      prog_type_cd: '000',
      prog_type: 'RR',
    },
    channels: [
      {
        plcmnt_opp_id: '7',
        offr_plcmnt_opp_strt_dt: '2023-10-09 23:59:59',
        offr_plcmnt_opp_end_dt: '2023-10-09 23:59:59',
        featured_offer_ind: 'N',
        media: [
          {
            media_url_loc_tx:
              'https://www.aexp-static.com/amexoffers/images/logos/00P5b00001XtmpLEAR',
            media_type_id: '2',
            media_loc_lang_ds: 'logo',
            language_cd: 'en',
            dia_cd: '03',
          },
          {
            media_url_loc_tx:
              'https://www.aexp-static.com/amexoffers/images/logos/00P5b00001XtmpLEAR',
            media_type_id: '11',
            media_loc_lang_ds: 'lifestyle image',
            language_cd: 'en',
            dia_cd: '03',
          },
        ],
        notifications: [
          {
            prtr_id: 'AAAA0001',
            mer_nm: '',
            language_cd: 'EN',
            ntfy_email_crit_tx: '',
            mer_url_ad_tx: '',
            trans_thld_ntfy_freq_ct: '',
            ntfy_seq_cd: 'RD01',
            from_email_ad_tx: '',
            ntfy_trgr_tx: '',
            cm_ntfy_mail_send_ts: '',
            email_subj_line_tx: '',
            ntfy_type_tx: 'CheetahMail Dynamic',
            ntfy_email_occr_cd: '',
            email_bdy_tx: '',
            event_type_tx: 'Redemption',
            spend_thld_ntfy_am: '',
            prop_card_in: 'Y',
            iso_alpha_2_ctry_cd: 'US',
            cmpgn_url_ad_tx: '',
            affl_id: '268935168',
            dia_cd: '03',
            mg_ref_id: '197625',
          },
          {
            prtr_id: 'AAAA0001',
            mer_nm: '',
            language_cd: 'EN',
            ntfy_email_crit_tx: '',
            mer_url_ad_tx: '',
            trans_thld_ntfy_freq_ct: '',
            ntfy_seq_cd: 'RD01',
            from_email_ad_tx: '',
            ntfy_trgr_tx: '',
            cm_ntfy_mail_send_ts: '',
            email_subj_line_tx: '',
            ntfy_type_tx: 'CheetahMail Dynamic',
            ntfy_email_occr_cd: '',
            email_bdy_tx: '',
            event_type_tx: 'Redemption',
            spend_thld_ntfy_am: '',
            prop_card_in: 'Y',
            iso_alpha_2_ctry_cd: 'US',
            cmpgn_url_ad_tx: '',
            affl_id: '268935168',
            dia_cd: '03',
            mg_ref_id: '197625',
          },
        ],
      },
      {
        plcmnt_opp_id: '16',
        offr_plcmnt_opp_strt_dt: '2023-10-09 23:59:59',
        offr_plcmnt_opp_end_dt: '2023-10-09 23:59:59',
        featured_offer_ind: 'N',
        media: [
          {
            media_url_loc_tx:
              'https://www.aexp-static.com/amexoffers/images/logos/00P5b00001XtmpLEAR',
            media_type_id: '2',
            media_loc_lang_ds: 'logo',
            language_cd: 'en',
            dia_cd: '03',
          },
          {
            media_url_loc_tx:
              'https://www.aexp-static.com/amexoffers/images/logos/00P5b00001XtmpLEAR',
            media_type_id: '11',
            media_loc_lang_ds: 'lifestyle image',
            language_cd: 'en',
            dia_cd: '03',
          },
        ],
        notifications: [
          {
            prtr_id: 'AAAA0001',
            mer_nm: '',
            language_cd: 'EN',
            ntfy_email_crit_tx: '',
            mer_url_ad_tx: '',
            trans_thld_ntfy_freq_ct: '',
            ntfy_seq_cd: 'RD01',
            from_email_ad_tx: '',
            ntfy_trgr_tx: '',
            cm_ntfy_mail_send_ts: '',
            email_subj_line_tx: '',
            ntfy_type_tx: 'CheetahMail Dynamic',
            ntfy_email_occr_cd: '',
            email_bdy_tx: '',
            event_type_tx: 'Redemption',
            spend_thld_ntfy_am: '',
            prop_card_in: 'Y',
            iso_alpha_2_ctry_cd: 'US',
            cmpgn_url_ad_tx: '',
            affl_id: '268935168',
            dia_cd: '03',
            mg_ref_id: '197625',
          },
          {
            prtr_id: 'AAAA0001',
            mer_nm: '',
            language_cd: 'EN',
            ntfy_email_crit_tx: '',
            mer_url_ad_tx: '',
            trans_thld_ntfy_freq_ct: '',
            ntfy_seq_cd: 'RD01',
            from_email_ad_tx: '',
            ntfy_trgr_tx: '',
            cm_ntfy_mail_send_ts: '',
            email_subj_line_tx: '',
            ntfy_type_tx: 'CheetahMail Dynamic',
            ntfy_email_occr_cd: '',
            email_bdy_tx: '',
            event_type_tx: 'Redemption',
            spend_thld_ntfy_am: '',
            prop_card_in: 'Y',
            iso_alpha_2_ctry_cd: 'US',
            cmpgn_url_ad_tx: '',
            affl_id: '268935168',
            dia_cd: '03',
            mg_ref_id: '197625',
          },
        ],
      },
    ],
    offr_loc_lang_dtl: {
      se_store_loctr_url_ad_tx: '',
      se_cust_cntc_url_ad_tx: '',
      se_cust_cntc_phone_no: '',
      se_cust_cntc_email_ad_tx: '',
      onln_rdm_url_ad_tx: 'http://www.lowes.com',
      alt_online_redemption_url: '',
      offr_rdm_cntc_phone_no: '',
      cnfr_email_ad_tx: 'stephanie.sebastian@aexp.com',
      requestor_name: '',
      secondary_requestor_name: '',
      secondary_requestor_email_ad: '',
    },
    offer_fulfillment: {
      xbrdr_vld_rqr_in: 'N',
      send_cm_trgt_file_in: '',
      scnd_rspbl_ctr_cd: '',
      scnd_fund_srce_id: '',
      rtrn_prd_ct: '90',
      rdm_per_ct: '',
      promo_id: '',
      prod_incl_excl_cd: '',
      prim_rspbl_ctr_cd: '',
      prim_fund_srce_id: '',
      ol_vld_rqr_in: 'N',
      offr_req_email_ad_tx: '',
      max_rwrd_cr_ct: '',
      lgr_curr_tx: 'USD',
      lgr_ctry_cd: '',
      indus_ctgy_cd: '1',
      grace_prd_ct: '90',
      fut_trans_disc_in: 'N',
      fund_se_no: '',
      fund_se_disc_usd_am: '',
      flfmt_fl_freq_cd: '',
      event_msg_id: '',
      elig_chk_rqr_in: 'N',
      disc_calc_cd: 'I',
      cmpgn_trans_prcs_curr_tx: 'USD',
      cmpgn_fund_strct_type_id: '',
      cmpgn_fund_max_thld_usd_am: '9.99999999999999E12',
      cmpgn_disc_offr_curr_tx: 'USD',
      cmpgn_allowable_curr_tx: 'USD',
      cm_ctry_tx: 'US',
      cheetah_mail_event_id: '',
      card_prod_incl_ds: '',
      card_prod_excl_ds: '',
      card_validation_req_flag: '',
      card_iss_cd: 'P',
      bns_point_incr_mult_no: '1.0',
      amex_fund_disc_usd_am: 'null',
      actl_se_disc_usd_am: 'null',
      offer_exclusions: [],
      offer_excluded_at: 'E/F',
    },
    offr_dur: {
      vld_end_ts: '2023-10-18 23:59:59',
      tz_no: 0,
      vld_strt_ts: '2023-10-09 00:00:00',
      disp_ts: '2023-10-09 00:00:00',
      disp_end_ts: '2023-10-13 23:59:59',
      offer_extended_end_date: '2023-10-18 23:59:59',
    },
    offer_details: {
      category_nm: 'Shopping',
      subctgy_nm: ['Home_and_Garden'],
      visibility_id: '1',
      super_offr_in: 'N',
      sm_mer_in: 'S',
      rdm_freq_ct: '2',
      offr_tier_in: '',
      offr_sta_cd: '01',
      offr_for_all_in: 'N',
      min_cumulative_mer_freq_ct: '',
      lst_updt_ts: '2023-10-13 00:02:13',
      fund_srce_type_cd: 'A',
      disc_rt: '',
      cstm_user_expc_nm: 'SFDC-GCOR-RC',
      couponless_in: 'Y',
      case_type_cd: 'F3',
      brnd_nm: '',
      offer_group_id: '0001074Member Week Business Offers0001073Member Week Hero Offers',
      default_language_indicator: 'Y',
      show_locations: 'N',
      lob_suppression_card_product_code:
        '0050005700400120011009001400130082003700930031005909BLM09MCY11ELANFS11USB_FP11USB_FPG11USB_MM0038003001500260039007802STANDARD00460080044002700700940041001006BARCLAYD106TRAVELOCITY07PENFED1',
      lob_suppression_card_group_code: '',
      action_flag: 'N',
      action_code: '',
      account_or_card_qual: 'CLB',
      partial_returns_supported: 'N',
      exclude_gift_card: 'N',
      poid: 'K6CX:0001',
      chain_offer_ind: 'I',
      campaign_path: 'D',
      bonus_tracker_ind: 'N',
      eligibility_suppression_period: '12',
      requestor_business_unit: 'Amex Travel',
      se_grouping_ind: 'N',
      se_agnostic_ind: 'N',
      control_percentage: '0',
      fair_lending_ind: 'N',
      available_to_all_ind: 'N',
      alcohol_flag: 'N',
      rolling_reminder_period_ind: 'N',
      gamer_suppression_ind: 'N',
      offer_goal: 'U',
      dynamic_offer_period_ind: 'N',
      dynamic_offer_redemption_period: '',
      dynamic_offer_extended_period: '',
      refresh_eligibility: 'NO',
      offer_monthly_reset_period: '',
      dynamic_date_resting_period: '',
      shop_small_ind: 'N/Y',
      dynamic_offer_ind: 'N/Y',
      smart_currency_exchange_offer_ind: 'N/Y',
      offer_enrollment_cap: '50',
      special_offer: '',
      state_code: 'AZ',
      campaign_enrollment_cap: '50',
      merchant_budget: '',
      promotional_component_id: '',
      loyalty_currency_code: 'USD',
      offer_early_tenure: '',
      auto_enrollment_flag: '',
      alternate_url_button_text: '',
      special_qual_criteria: '',
      addenda_type: '',
      gabm_event_id: '',
      multi_redemption_range: '',
      fp_personalization_ind: '',
      fp_random_execution_period: '',
      max_redemption_notification_count: '',
      max_reminder_notification_percent_count: '',
    },
    offer_display_copy: [
      {
        language_cd: 'en',
        offer_name: "Lowe's - Member Week Offer",
        terms_and_cond_tx:
          "Must first add offer to an eligible Card by 10/13/2023 and then use same Card to make one or more qualifying purchases totaling $200 or more in-store at Lowe’s or online at lowes.com by 10/18/2023 to receive a one-time statement credit of $50. Only U.S.-issued Business American Express® Cards are eligible. American Express Consumer Cards, Prepaid Cards, Corporate Cards, and American Express Cards issued outside the US are not eligible for the offer. Limit 1 enrolled Card per Card Member across all American Express offer channels. Your enrollment of an eligible American Express Card for this offer extends only to that Card. Offer valid in-store at Lowe's and online only at US website lowes.com. Valid at participating locations in the US. Excludes Lowe's Outlet locations, LowesforPros.com, and any Lowe’s branded website that is operated by a third party on behalf of Lowe’s, including but not limited to applianceparts.lowes.com, lowesstore.wgiftcard.com, blinds.lowes.com. Excludes electronic and corporate gift card purchases. Not valid on purchases shipped outside of the US. See merchant website for shipping policy. Some merchants may not ship to all areas. Offer is non-transferable. Valid only on purchases made in US dollars. Limit of 1 statement credit per Card Member. You may not receive the statement credit if we receive inaccurate information or are otherwise unable to identify your purchase as qualifying for the offer. For example, you may not receive the statement credit if (a) the merchant uses a third-party to sell their products or services; or (b) the merchant uses a third-party to process or submit your transaction to us (e.g., using mobile or wireless card readers); or (c) you choose to make a purchase using a third-party payment account or make a purchase using a mobile or digital wallet. Purchases may fall outside of the offer period in some cases due to a delay in merchants submitting transactions to us or if the purchase date differs from the date you made the transaction (for example, the purchase date for online orders may be the shipping date). Statement credit will appear on your billing statement within 90 days after 10/18/2023, provided that American Express receives information from the merchant about your qualifying purchase. Note that American Express may not receive information about your qualifying purchase from merchant until all items/services from your qualifying purchase have been shipped/provided by merchant. Statement credit may be reversed if qualifying purchase is returned/cancelled. If American Express does not receive information that identifies your purchase as qualifying for the offer, you will not receive the statement credit. Limit 1 enrolled Card per American Express Card online account. The enrolled Card account must be active, not past due, canceled, or have a returned payment outstanding to receive the statement credit. Any benefit earned from this offer is in addition to the rewards (i.e. Membership Rewards or cash back) earned as part of your existing Card benefits, but your ability to earn spend-based rewards for the purchase will be based on the amount after any statement credit or other discount is applied. For questions regarding your Card Account, please call the number on the back of your Card. By adding an offer to a Card, you agree that American Express may send you communications about the offer. POID: K6CX:0001",
        stmt_cr_line_disc: 'Amex Offer Credit',
        stmt_cr_line_disc_rvs: 'Amex Offer Return',
        summary_copy: 'Spend $200 or more, get $50 back. Enroll by 10/13/2023.',
        claim_copy:
          'Enroll by 10/13/2023. Get a one-time $50 statement credit by using your enrolled eligible Business Card to spend a minimum of $200 in one or more purchases in-store at Lowe’s or online at lowes.com by 10/18/2023. Excludes outlet locations. See terms.',
        offer_construct: '$50 back',
        campaign_name: "Lowe's  - Member Week 2023 Offer",
        dia_cd: '03',
      },
      {
        language_cd: 'fr',
        offer_name: "Lowe's - Member Week Offer",
        terms_and_cond_tx:
          "Must first add offer to an eligible Card by 10/13/2023 and then use same Card to make one or more qualifying purchases totaling $200 or more in-store at Lowe’s or online at lowes.com by 10/18/2023 to receive a one-time statement credit of $50. Only U.S.-issued Business American Express® Cards are eligible. American Express Consumer Cards, Prepaid Cards, Corporate Cards, and American Express Cards issued outside the US are not eligible for the offer. Limit 1 enrolled Card per Card Member across all American Express offer channels. Your enrollment of an eligible American Express Card for this offer extends only to that Card. Offer valid in-store at Lowe's and online only at US website lowes.com. Valid at participating locations in the US. Excludes Lowe's Outlet locations, LowesforPros.com, and any Lowe’s branded website that is operated by a third party on behalf of Lowe’s, including but not limited to applianceparts.lowes.com, lowesstore.wgiftcard.com, blinds.lowes.com. Excludes electronic and corporate gift card purchases. Not valid on purchases shipped outside of the US. See merchant website for shipping policy. Some merchants may not ship to all areas. Offer is non-transferable. Valid only on purchases made in US dollars. Limit of 1 statement credit per Card Member. You may not receive the statement credit if we receive inaccurate information or are otherwise unable to identify your purchase as qualifying for the offer. For example, you may not receive the statement credit if (a) the merchant uses a third-party to sell their products or services; or (b) the merchant uses a third-party to process or submit your transaction to us (e.g., using mobile or wireless card readers); or (c) you choose to make a purchase using a third-party payment account or make a purchase using a mobile or digital wallet. Purchases may fall outside of the offer period in some cases due to a delay in merchants submitting transactions to us or if the purchase date differs from the date you made the transaction (for example, the purchase date for online orders may be the shipping date). Statement credit will appear on your billing statement within 90 days after 10/18/2023, provided that American Express receives information from the merchant about your qualifying purchase. Note that American Express may not receive information about your qualifying purchase from merchant until all items/services from your qualifying purchase have been shipped/provided by merchant. Statement credit may be reversed if qualifying purchase is returned/cancelled. If American Express does not receive information that identifies your purchase as qualifying for the offer, you will not receive the statement credit. Limit 1 enrolled Card per American Express Card online account. The enrolled Card account must be active, not past due, canceled, or have a returned payment outstanding to receive the statement credit. Any benefit earned from this offer is in addition to the rewards (i.e. Membership Rewards or cash back) earned as part of your existing Card benefits, but your ability to earn spend-based rewards for the purchase will be based on the amount after any statement credit or other discount is applied. For questions regarding your Card Account, please call the number on the back of your Card. By adding an offer to a Card, you agree that American Express may send you communications about the offer. POID: K6CX:0001",
        stmt_cr_line_disc: 'Amex Offer Credit',
        stmt_cr_line_disc_rvs: 'Amex Offer Return',
        summary_copy: 'Spend $200 or more, get $50 back. Enroll by 10/13/2023.',
        claim_copy:
          'Enroll by 10/13/2023. Get a one-time $50 statement credit by using your enrolled eligible Business Card to spend a minimum of $200 in one or more purchases in-store at Lowe’s or online at lowes.com by 10/18/2023. Excludes outlet locations. See terms.',
        offer_construct: '$50 back',
        campaign_name: "Lowe's  - Member Week 2023 Offer",
        dia_cd: '03',
      },
    ],
    mle_list: {
      mle_list_id: ['114086'],
      peerlist_id: ['114086'],
      mle_list_updated_ind: 'Y',
      mle_list_last_update_ts: '2023-10-13 23:59:59',
    },
    bin_range_details: [],
    bin_range_indicator: '',
    payment_method: '',
    payment_product_type: '',
    funding_struct_dtls: {
      funding_srce_options: [
        {
          funding_option_cd: '002',
          aggregated_fund_thld_amt: '100',
          funding_srce_dtls: [
            {
              responsibility_center: '401309',
              offr_funding_struct: '002+218',
              funding_srce_order: '1',
              fund_disc: '50',
              funding_srce: 'OPEN',
              max_offr_fund_thld_amt: '100',
              fund_se_nm: '',
            },
          ],
        },
      ],
      aggregated_fund_disc: '',
    },
    invoice_details: {
      merchant_tier: 'Unmanaged Merchants',
      campaign_sponsor: '',
      invoice_req_ind: 'Y',
      purchase_order_number: '',
      billing_contact_details: [
        {
          type: 'primary',
          name: '',
          email_id: '',
          phone_number: '',
          street_address: '',
          city: '',
          state: '',
          zip: '',
          country: '',
        },
      ],
      client_manager_name: '',
      client_manager_email: '',
      marketing_consultant_name: '',
      marketing_consultant_email: '',
    },
    aqr: {
      comment: '',
      addendas: {
        addenda: [
          {
            type: '0301_Airline',
            rules: {
              relation: 'AND',
              rule: [
                {
                  scope: 'Include',
                  name: '13_HM_ENR_TAA_AIR_IATA_NUM_CD',
                  pattern_match: 'Strict',
                  values: ['03531500', '22615412', '03972673', '03577523', '14644324', '50719546'],
                },
              ],
            },
          },
        ],
      },
    },
    elig_crit: {
      min_cumlt_mer_spend_am: '',
      max_award_cap_am: '9999999999999.99',
      disc_am: '23.00',
      max_cumlt_mer_spend_am: '9999999999999.99',
      max_trans_am: '9999999999999.99',
      iso_alpha_3_curr_cd: 'USD',
      min_trans_am: '233.00',
    },
  },
}
